bankid:
  baseUrl: https://appapi2.test.bankid.com/
  authentication-requirements:
    certificate-policies:
      - "1.2.3.4.5"      # BankID on file
      - "1.2.3.4.10"     # BankID on smart card
      - "1.2.3.4.25"     # Mobile BankID
      - "1.2.752.71.1.3" # Nordea e-id on file and on smart card
      - "1.2.752.60.1.6" # Test BankID for some BankID Banks
  client-cert-store-path: certificates/test/FPTestcert4_20220818.p12
  client-cert-store-password: qwerty123
  trust-store-path: certificates/test/truststore.p12
  trust-store-password: qwerty123
spring:
  ssl:
    bundle:
      jks:
        bankid-client:
          keystore:
            location: "classpath:FPTestcert4_20230629.p12"
            password: "qwerty123"
            type: "PKCS12"
          truststore:
            location: "classpath:truststore.p12"
            password: "qwerty123"
            type: "PKCS12"
  cache:
    cache-names: user-authentication-request


